### ISSUE TITLE
Can't invoke simple commands

### ISSUE THREAD

**Issue by mrcat323** [ParthKolekar/c-shell#1]
Hey @ParthKolekar. I'm C beginner, but I've got a few questions for you, about this project.
* Why it doesn't work normally ?
* It can't do simple commands like `cd` or something else

Here you are:
![image](https://user-images.githubusercontent.com/23054662/73067002-5abe7000-3ec9-11ea-8932-85a871805c2c.png)
It even **doesn't write directory name if it doesn't exist** and doesn't go to existing directories

**Comment by ParthKolekar** [comment]
`cd` isn't an executable. It is a bash built-in command.

Could you please clarify about the other queries?

**Comment by ParthKolekar** [comment]
Closing this because I don't think I'll be implementing the changes.

**Comment by mrcat323** [comment]
> Closing this because I don't think I'll be implementing the changes.

Why not ?

**Comment by mrcat323** [comment]
> Closing this because I don't think I'll be implementing the changes.

Why you not use bash's built in then ?

**Comment by ParthKolekar** [comment]
The bash built-in is a command that's used in the bash shell. I do not see how I'll be able to make use of it in this project.

I've stopped working on this project a while ago. Please feel free to clone and work on implementing the features requested.

**Comment by mrcat323** [comment]
> The bash built-in is a command that's used in the bash shell. I do not see how I'll be able to make use of it in this project.
> 
> I've stopped working on this project a while ago. Please feel free to clone and work on implementing the features requested.

Okay, thanks for responding
